apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-configmap
  labels:
    chart: "{{ .Chart.Name }}"
    app: "{{ .Values.global.name }}"
data:
  opensearch : |
  {{- include "opensearch" . | nindent 4}}
  jvm.options: |
  {{- include "jvm.options" . | nindent 4}}
  opensearch.yml: |
  {{- include "opensearch.yml" . | nindent 4}}
  log4j2.properties: |
  {{- include "log4j2.properties" . | nindent 4}}