apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.namespace }}
  name: apidoc-opensearch-logs
  labels:
    cattle.io/creator: norman
spec:
  storageClassName: csi-rbd-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
