apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-service
  labels:
    app.kubernetes.io/name: {{  .Values.global.name  }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.httpPort }}
    - name: transport
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.transportPort }}
  selector:
    app.kubernetes.io/name: {{  .Values.global.name  }}
    app.kubernetes.io/instance: {{ .Values.global.name }}